name: Build Kivy Android App

on:
  push:
    branches:
      - main  # Change this to your default branch if necessary
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'  # Specify the Python version you need

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-pip python3-setuptools python3-wheel
          pip install buildozer

      - name: Build the app
        run: |
          cd frost_base_converter  # Change this to your project directory if needed
          buildozer -v android debug  # Change 'debug' to 'release' for a production build

      - name: Upload APK
        uses: actions/upload-artifact@v3  # Updated to v3
        with:
          name: frost_base_converter-apk
          path: frost_base_converter/bin/*.apk  # Adjust if your APK is saved in a different location
