on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build APK
        uses: digreatbrian/buildozer-action@v2
        with:
          buildozer-cmd: buildozer -v android debug
          workdir: .  # Change this from work-dir to workdir

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: package
          path: ./bin/*.apk
